name: Run AGLint
on:
  push:
    branches:
      - '**'
permissions:
    actions: read
    contents: read
jobs:
  lint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run AGLint
        run: npm run lint
